// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2zf_YVp0K-p5aQWGloCe-kQFsoAnWI-0',
    appId: '1:1065979739507:web:10720428390c1cab951906',
    messagingSenderId: '1065979739507',
    projectId: 'earthquake-5b60b',
    authDomain: 'earthquake-5b60b.firebaseapp.com',
    storageBucket: 'earthquake-5b60b.firebasestorage.app',
    measurementId: 'G-LDV00CX312',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2EYPBiG-XZuKQsktJgTcttcp_Rbq42ac',
    appId: '1:1065979739507:android:52256f113d7a6f73951906',
    messagingSenderId: '1065979739507',
    projectId: 'earthquake-5b60b',
    storageBucket: 'earthquake-5b60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV1qvFkYcVj6-AKgqFvKINcBxkkPbkgjk',
    appId: '1:1065979739507:ios:15490e44b3b709f8951906',
    messagingSenderId: '1065979739507',
    projectId: 'earthquake-5b60b',
    storageBucket: 'earthquake-5b60b.firebasestorage.app',
    iosBundleId: 'com.example.thaiThermo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV1qvFkYcVj6-AKgqFvKINcBxkkPbkgjk',
    appId: '1:1065979739507:ios:15490e44b3b709f8951906',
    messagingSenderId: '1065979739507',
    projectId: 'earthquake-5b60b',
    storageBucket: 'earthquake-5b60b.firebasestorage.app',
    iosBundleId: 'com.example.thaiThermo3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2zf_YVp0K-p5aQWGloCe-kQFsoAnWI-0',
    appId: '1:1065979739507:web:385a59c8c16e1f1f951906',
    messagingSenderId: '1065979739507',
    projectId: 'earthquake-5b60b',
    authDomain: 'earthquake-5b60b.firebaseapp.com',
    storageBucket: 'earthquake-5b60b.firebasestorage.app',
    measurementId: 'G-1FFS28PJWS',
  );
}
